-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE FUNCTION public.active_users_ratio()
--  RETURNS SETOF count_by_date
--  LANGUAGE sql
--  STABLE
-- AS $function$
--     SELECT date, SUM(users_monthly)::float / SUM(users_total) as count from thefederation_stat WHERE node_id IS NOT NULL AND date > NOW() - INTERVAL '1 year' group by date
-- $function$;
