# Generated by Django 2.0.3 on 2018-04-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thefederation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='admin_email',
        ),
        migrations.AddField(
            model_name='node',
            name='organization_account',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='node',
            name='organization_contact',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='node',
            name='organization_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
