# Generated by Django 2.0.3 on 2018-04-08 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thefederation', '0003_auto_20180408_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('users_total', models.PositiveIntegerField(null=True)),
                ('users_half_year', models.PositiveIntegerField(null=True)),
                ('users_monthly', models.PositiveIntegerField(null=True)),
                ('users_weekly', models.PositiveIntegerField(null=True)),
                ('local_posts', models.PositiveIntegerField(null=True)),
                ('local_comments', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='node',
            name='failures',
        ),
        migrations.AddField(
            model_name='node',
            name='last_success',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='thefederation.Node'),
        ),
    ]
