# Generated by Django 2.0.3 on 2018-04-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thefederation', '0004_auto_20180408_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='code',
            field=models.URLField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='platform',
            name='display_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='platform',
            name='first_release',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='license',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='platform',
            name='website',
            field=models.URLField(blank=True, max_length=128),
        ),
    ]
