# Generated by Django 2.0.3 on 2018-04-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thefederation', '0011_add_some_indexes_to_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='version_clean_Style',
            field=models.CharField(choices=[('none', 'none'), ('remove_after_dash', 'remove_after_dash')], default='none', max_length=30),
        ),
    ]
