# Generated by Django 2.0.3 on 2018-04-29 18:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thefederation', '0013_alter_indexes_on_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='features',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='node',
            name='protocols',
            field=models.ManyToManyField(blank=True, related_name='nodes', to='thefederation.Protocol'),
        ),
        migrations.AlterField(
            model_name='node',
            name='server_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='node',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='nodes', to='thefederation.Service'),
        ),
    ]
