# Generated by Django 2.0.3 on 2018-05-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thefederation', '0015_add_more_columns_to_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='version_clean_Style',
            new_name='version_clean_style',
        ),
    ]
