# Generated by Django 2.0.3 on 2018-05-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thefederation', '0016_fix_typo_in_version_clean_style_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='display_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='protocol',
            name='website',
            field=models.URLField(blank=True, max_length=128),
        ),
    ]
