# Generated by Django 2.0.3 on 2018-06-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thefederation', '0017_add_more_fields_to_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='version_clean_style',
            field=models.CharField(choices=[('none', 'none'), ('remove_after_dash', 'remove_after_dash'), ('remove_commit_hash', 'remove_commit_hash')], default='none', max_length=30),
        ),
    ]
