# Generated by Django 2.0.13 on 2019-10-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thefederation', '0018_add_remove_commit_hash_version_clean_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='organization_account',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='node',
            name='organization_contact',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='node',
            name='organization_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
