when:
  branch: main

variables:
  - &platforms 'linux/amd64'

steps:
  frontend-dryrun:
    image: woodpeckerci/plugin-kaniko
    settings:
      dockerfile: docker/nginx/Dockerfile
      platforms: *platforms
      no_push: true
      repo: a6543/the-federation_frontend
      tags: test
    when:
      event: pull_request
    depends_on: []

  frontend-publish:
    image: woodpeckerci/plugin-kaniko
    settings:
      dockerfile: docker/nginx/Dockerfile
      platforms: *platforms
      repo: a6543/the-federation_frontend
      tags: latest,v1-${CI_COMMIT_SHA:0:8}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event: ["push", "tag"]

  backend-dryrun:
    image: woodpeckerci/plugin-docker-buildx:6
    settings:
      dockerfile: docker/app/Dockerfile
      platforms: *platforms
      dry_run: true
      repo: a6543/the-federation_backend
      tags: test
      build_args:
        MAXMIND_LICENSE_KEY:
          from_secret: MAXMIND_LICENSE_KEY
    when:
      event: pull_request

  backend-publish:
    image: woodpeckerci/plugin-docker-buildx:6
    settings:
      dockerfile: docker/app/Dockerfile
      platforms: *platforms
      repo: a6543/the-federation_backend
      tags: latest,v1-${CI_COMMIT_SHA:0:8}
      build_args:
        MAXMIND_LICENSE_KEY:
          from_secret: MAXMIND_LICENSE_KEY
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event: ["push", "tag"]
